t='''


SELECT PL.PLAYER_SURNAME
FROM PLAYER PL
WHERE
PL.PLAYER_ID IN
    (SELECT P.PLAYER_ID, COUNT(P.PLAYER_ID)
    FROM (PLAYER P JOIN PLAYER_TEAM PT ON PT.PLAYER_ID = P.PLAYER_ID)
    GROUP BY P.PLAYER_ID
    ORDER BY COUNT(P.PLAYER_ID) DESC);'''


print(t[212:])
print("\n\n\n" + t[:212])


